name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main


jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/library/tomcat:latest'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'
          vuln-type: 'os,library'      
      
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin' 
      
      - name: Set up Maven 3
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.0'
      
      - name: Build artifact
        run: mvn clean package -DskipTests

      # - name: Test
      #   run: mvn test

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1' # Change to your region
          APPLICATION_NAME: 'lumiatech-tomcat-app'
          ENVIRONMENT_NAME: 'lumiatech-tomcat-app-env'
        run: |
          echo "Deploying to Elastic Beanstalk..."
          # Create a ZIP file from the WAR file
          cp target/lumiatech-v1.war ROOT.war
          zip -r ROOT.zip ROOT.war
          aws s3 cp ROOT.zip s3://ndzenyuy-test-bucket/ROOT.zip
          
          # Deploy the ZIP file using the AWS CLI
          aws elasticbeanstalk create-application-version --application $APPLICATION_NAME --version-label $GITHUB_RUN_NUMBER --source-bundle S3Bucket=ndzenyuy-test-bucket,S3Key=ROOT.zip
          aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_RUN_NUMBER

        
      # - name: Clean up 
      #   run: echo "Cleaning up after the deployment..."